app:
  build: ../../
  dockerfile: docker/release/Dockerfile
  links:
    - db
  volumes_from:
    - webroot
  environment:
    DJANGO_SETTINGS_MODULE: todoBackend.settings.release
    MYSQL_HOST: db
    MYSQL_USER: wissem
    MYSQL_PASSWORD: wissem
  command: 
    - uwsgi
    - "--socket /var/www/todobackend/todobackend.sock"
    - "--chmod-socket=666"
    - "--module todoBackend.wsgi"
    - "--master"
    - "--die-on-term"

test:
  image: wiss013/todobackend-spec
  links:
    - nginx
  environment:
    URL: http://nginx:8000/todos
    JUNIT_REPORT_PATH: /reports/acceptance.xml
    JUNIT_REPORT_STACK: 1
  command: --reporter mocha-jenkins-reporter

nginx:
  image: nginx
  links:
    - app
  volumes:
    - ./todobackend.conf:/etc/nginx/conf.d/todobackend.conf
  ports:
    - "8000:8000"
  volumes_from:
    - webroot

webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes:
    - /var/www/todobackend
  entrypoint: "true"


db:
  image: mysql:5.6
  expose: 
    - "3306"
  environment:
    MYSQL_DATABASE: todobackend
    MYSQL_USER: wissem
    MYSQL_PASSWORD: wissem
    MYSQL_ROOT_PASSWORD: wissem


agent:
  image: wiss013/ansible
  volumes:
    - ../../ansible/probe.yml/:/ansible/site.yml
  links:
    - db
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"

